COPY INTO claims_dw.raw.raw_claims (
    beneficiary_id,
    claim_id,
    near_line_record_code,
    claim_type_code,
    claim_start_date,
    claim_end_date,
    weekly_processing_date,
    fiscal_processing_date,
    claim_query_code,
    provider_number,
    facility_type_code,
    service_classification_code,
    claim_frequency_code,
    fiscal_intermediary_number,
    medicare_non_payment_reason_code,
    claim_payment_amount,
    primary_payer_payment_amount,
    primary_payer_code,
    claim_action_code,
    provider_state_code,
    organization_npi_number,
    attending_physician_upin,
    attending_physician_npi,
    operating_physician_upin,
    operating_physician_npi,
    other_physician_upin,
    other_physician_npi,
    managed_care_plan_switch,
    patient_discharge_status_code,
    pps_indicator_code,
    total_charge_amount,
    admission_date,
    admission_type_code,
    admission_source_code,
    patient_status_indicator,
    pass_through_per_diem_amount,
    inpatient_deductible_amount,
    coinsurance_liability_amount,
    blood_deductible_amount,
    professional_component_charge_amount,
    non_covered_charge_amount,
    total_deduction_amount,
    total_pps_capital_amount,
    pps_capital_federal_specific_amount,
    pps_capital_outlier_amount,
    pps_capital_disproportionate_share_amount,
    pps_capital_indirect_medical_education_amount,
    pps_capital_exception_payment_amount,
    pps_old_capital_hold_harmless_amount,
    pps_drg_weight,
    utilization_day_count,
    total_coinsurance_days_count,
    lifetime_reserve_days_used,
    non_utilization_days_count,
    blood_units_furnished_quantity,
    uncovered_stay_start_date,
    uncovered_stay_end_date,
    covered_care_end_date,
    benefits_exhaustion_date,
    patient_discharge_date,
    drg_code,
    drg_outlier_stay_code,
    approved_drg_outlier_payment_amount,
    admitting_diagnosis_code,
    principal_diagnosis_code,
    icd_diagnosis_code1,
    poa_indicator1,
    icd_diagnosis_code2,
    poa_indicator2,
    icd_diagnosis_code3,
    poa_indicator3,
    icd_diagnosis_code4,
    poa_indicator4,
    icd_diagnosis_code5,
    poa_indicator5,
    icd_diagnosis_code6,
    poa_indicator6,
    icd_diagnosis_code7,
    poa_indicator7,
    icd_diagnosis_code8,
    poa_indicator8,
    icd_diagnosis_code9,
    poa_indicator9,
    icd_diagnosis_code10,
    poa_indicator10,
    icd_diagnosis_code11,
    poa_indicator11,
    icd_diagnosis_code12,
    poa_indicator12,
    icd_diagnosis_code13,
    poa_indicator13,
    icd_diagnosis_code14,
    poa_indicator14,
    icd_diagnosis_code15,
    poa_indicator15,
    icd_diagnosis_code16,
    poa_indicator16,
    icd_diagnosis_code17,
    poa_indicator17,
    icd_diagnosis_code18,
    poa_indicator18,
    icd_diagnosis_code19,
    poa_indicator19,
    icd_diagnosis_code20,
    poa_indicator20,
    icd_diagnosis_code21,
    poa_indicator21,
    icd_diagnosis_code22,
    poa_indicator22,
    icd_diagnosis_code23,
    poa_indicator23,
    icd_diagnosis_code24,
    poa_indicator24,
    icd_diagnosis_code25,
    poa_indicator25,
    first_external_diagnosis_code,
    external_diagnosis_code1,
    external_poa_indicator1,
    external_diagnosis_code2,
    external_poa_indicator2,
    external_diagnosis_code3,
    external_poa_indicator3,
    external_diagnosis_code4,
    external_poa_indicator4,
    external_diagnosis_code5,
    external_poa_indicator5,
    external_diagnosis_code6,
    external_poa_indicator6,
    external_diagnosis_code7,
    external_poa_indicator7,
    external_diagnosis_code8,
    external_poa_indicator8,
    external_diagnosis_code9,
    external_poa_indicator9,
    external_diagnosis_code10,
    external_poa_indicator10,
    external_diagnosis_code11,
    external_poa_indicator11,
    external_diagnosis_code12,
    external_poa_indicator12,
    icd_procedure_code1,
    procedure_date1,
    icd_procedure_code2,
    procedure_date2,
    icd_procedure_code3,
    procedure_date3,
    icd_procedure_code4,
    procedure_date4,
    icd_procedure_code5,
    procedure_date5,
    icd_procedure_code6,
    procedure_date6,
    icd_procedure_code7,
    procedure_date7,
    icd_procedure_code8,
    procedure_date8,
    icd_procedure_code9,
    procedure_date9,
    icd_procedure_code10,
    procedure_date10,
    icd_procedure_code11,
    procedure_date11,
    icd_procedure_code12,
    procedure_date12,
    icd_procedure_code13,
    procedure_date13,
    icd_procedure_code14,
    procedure_date14,
    icd_procedure_code15,
    procedure_date15,
    icd_procedure_code16,
    procedure_date16,
    icd_procedure_code17,
    procedure_date17,
    icd_procedure_code18,
    procedure_date18,
    icd_procedure_code19,
    procedure_date19,
    icd_procedure_code20,
    procedure_date20,
    icd_procedure_code21,
    procedure_date21,
    icd_procedure_code22,
    procedure_date22,
    icd_procedure_code23,
    procedure_date23,
    icd_procedure_code24,
    procedure_date24,
    icd_procedure_code25,
    procedure_date25,
    uncompensated_care_payment_amount,
    line_number,
    revenue_center_code,
    hcpcs_code,
    deductible_coinsurance_code,
    source_file_name,
    loaded_timestamp
)
FROM (
    SELECT
        $1 AS beneficiary_id,
        $2 AS claim_id,
        $3 AS near_line_record_code,
        $4 AS claim_type_code,
        TO_DATE($5, 'DD-MON-YYYY') AS claim_start_date,
        TO_DATE($6, 'DD-MON-YYYY') AS claim_end_date,
        TO_DATE($7, 'DD-MON-YYYY') AS weekly_processing_date,
        TO_DATE($8, 'DD-MON-YYYY') AS fiscal_processing_date,
        $9 AS claim_query_code,
        $10 AS provider_number,
        $11 AS facility_type_code,
        $12 AS service_classification_code,
        $13 AS claim_frequency_code,
        $14 AS fiscal_intermediary_number,
        $15 AS medicare_non_payment_reason_code,
        CAST($16 AS NUMERIC(18, 2)) AS claim_payment_amount,
        CAST($17 AS NUMERIC(18, 2)) AS primary_payer_payment_amount,
        $18 AS primary_payer_code,
        $19 AS claim_action_code,
        $20 AS provider_state_code,
        $21 AS organization_npi_number,
        $22 AS attending_physician_upin,
        $23 AS attending_physician_npi,
        $24 AS operating_physician_upin,
        $25 AS operating_physician_npi,
        $26 AS other_physician_upin,
        $27 AS other_physician_npi,
        $28 AS managed_care_plan_switch,
        $29 AS patient_discharge_status_code,
        $30 AS pps_indicator_code,
        CAST($31 AS NUMERIC(18, 2)) AS total_charge_amount,
        TO_DATE($32, 'DD-MON-YYYY') AS admission_date,
        $33 AS admission_type_code,
        $34 AS admission_source_code,
        $35 AS patient_status_indicator,
        CAST($36 AS NUMERIC(18, 2)) AS pass_through_per_diem_amount,
        CAST($37 AS NUMERIC(18, 2)) AS inpatient_deductible_amount,
        CAST($38 AS NUMERIC(18, 2)) AS coinsurance_liability_amount,
        CAST($39 AS NUMERIC(18, 2)) AS blood_deductible_amount,
        CAST($40 AS NUMERIC(18, 2)) AS professional_component_charge_amount,
        CAST($41 AS NUMERIC(18, 2)) AS non_covered_charge_amount,
        CAST($42 AS NUMERIC(18, 2)) AS total_deduction_amount,
        CAST($43 AS NUMERIC(18, 2)) AS total_pps_capital_amount,
        CAST($44 AS NUMERIC(18, 2)) AS pps_capital_federal_specific_amount,
        CAST($45 AS NUMERIC(18, 2)) AS pps_capital_outlier_amount,
        CAST($46 AS NUMERIC(18, 2)) AS pps_capital_disproportionate_share_amount,
        CAST($47 AS NUMERIC(18, 2)) AS pps_capital_indirect_medical_education_amount,
        CAST($48 AS NUMERIC(18, 2)) AS pps_capital_exception_payment_amount,
        CAST($49 AS NUMERIC(18, 2)) AS pps_old_capital_hold_harmless_amount,
        CAST($50 AS NUMERIC(18, 4)) AS pps_drg_weight,
        CAST($51 AS INTEGER) AS utilization_day_count,
        CAST($52 AS INTEGER) AS total_coinsurance_days_count,
        CAST($53 AS INTEGER) AS lifetime_reserve_days_used,
        CAST($54 AS INTEGER) AS non_utilization_days_count,
        CAST($55 AS INTEGER) AS blood_units_furnished_quantity,
        TO_DATE($56, 'DD-MON-YYYY') AS uncovered_stay_start_date,
        TO_DATE($57, 'DD-MON-YYYY') AS uncovered_stay_end_date,
        TO_DATE($58, 'DD-MON-YYYY') AS covered_care_end_date,
        TO_DATE($59, 'DD-MON-YYYY') AS benefits_exhaustion_date,
        TO_DATE($60, 'DD-MON-YYYY') AS patient_discharge_date,
        $61 AS drg_code,
        $62 AS drg_outlier_stay_code,
        CAST($63 AS NUMERIC(18, 2)) AS approved_drg_outlier_payment_amount,
        $64 AS admitting_diagnosis_code,
        $65 AS principal_diagnosis_code,
        $66 AS icd_diagnosis_code1,
        $67 AS poa_indicator1,
        $68 AS icd_diagnosis_code2,
        $69 AS poa_indicator2,
        $70 AS icd_diagnosis_code3,
        $71 AS poa_indicator3,
        $72 AS icd_diagnosis_code4,
        $73 AS poa_indicator4,
        $74 AS icd_diagnosis_code5,
        $75 AS poa_indicator5,
        $76 AS icd_diagnosis_code6,
        $77 AS poa_indicator6,
        $78 AS icd_diagnosis_code7,
        $79 AS poa_indicator7,
        $80 AS icd_diagnosis_code8,
        $81 AS poa_indicator8,
        $82 AS icd_diagnosis_code9,
        $83 AS poa_indicator9,
        $84 AS icd_diagnosis_code10,
        $85 AS poa_indicator10,
        $86 AS icd_diagnosis_code11,
        $87 AS poa_indicator11,
        $88 AS icd_diagnosis_code12,
        $89 AS poa_indicator12,
        $90 AS icd_diagnosis_code13,
        $91 AS poa_indicator13,
        $92 AS icd_diagnosis_code14,
        $93 AS poa_indicator14,
        $94 AS icd_diagnosis_code15,
        $95 AS poa_indicator15,
        $96 AS icd_diagnosis_code16,
        $97 AS poa_indicator16,
        $98 AS icd_diagnosis_code17,
        $99 AS poa_indicator17,
        $100 AS icd_diagnosis_code18,
        $101 AS poa_indicator18,
        $102 AS icd_diagnosis_code19,
        $103 AS poa_indicator19,
        $104 AS icd_diagnosis_code20,
        $105 AS poa_indicator20,
        $106 AS icd_diagnosis_code21,
        $107 AS poa_indicator21,
        $108 AS icd_diagnosis_code22,
        $109 AS poa_indicator22,
        $110 AS icd_diagnosis_code23,
        $111 AS poa_indicator23,
        $112 AS icd_diagnosis_code24,
        $113 AS poa_indicator24,
        $114 AS icd_diagnosis_code25,
        $115 AS poa_indicator25,
        $116 AS first_external_diagnosis_code,
        $117 AS external_diagnosis_code1,
        $118 AS external_poa_indicator1,
        $119 AS external_diagnosis_code2,
        $120 AS external_poa_indicator2,
        $121 AS external_diagnosis_code3,
        $122 AS external_poa_indicator3,
        $123 AS external_diagnosis_code4,
        $124 AS external_poa_indicator4,
        $125 AS external_diagnosis_code5,
        $126 AS external_poa_indicator5,
        $127 AS external_diagnosis_code6,
        $128 AS external_poa_indicator6,
        $129 AS external_diagnosis_code7,
        $130 AS external_poa_indicator7,
        $131 AS external_diagnosis_code8,
        $132 AS external_poa_indicator8,
        $133 AS external_diagnosis_code9,
        $134 AS external_poa_indicator9,
        $135 AS external_diagnosis_code10,
        $136 AS external_poa_indicator10,
        $137 AS external_diagnosis_code11,
        $138 AS external_poa_indicator11,
        $139 AS external_diagnosis_code12,
        $140 AS external_poa_indicator12,
        $141 AS icd_procedure_code1,
        TO_DATE($142, 'DD-MON-YYYY') AS procedure_date1,
        $143 AS icd_procedure_code2,
        TO_DATE($144, 'DD-MON-YYYY') AS procedure_date2,
        $145 AS icd_procedure_code3,
        TO_DATE($146, 'DD-MON-YYYY') AS procedure_date3,
        $147 AS icd_procedure_code4,
        TO_DATE($148, 'DD-MON-YYYY') AS procedure_date4,
        $149 AS icd_procedure_code5,
        TO_DATE($150, 'DD-MON-YYYY') AS procedure_date5,
        $151 AS icd_procedure_code6,
        TO_DATE($152, 'DD-MON-YYYY') AS procedure_date6,
        $153 AS icd_procedure_code7,
        TO_DATE($154, 'DD-MON-YYYY') AS procedure_date7,
        $155 AS icd_procedure_code8,
        TO_DATE($156, 'DD-MON-YYYY') AS procedure_date8,
        $157 AS icd_procedure_code9,
        TO_DATE($158, 'DD-MON-YYYY') AS procedure_date9,
        $159 AS icd_procedure_code10,
        TO_DATE($160, 'DD-MON-YYYY') AS procedure_date10,
        $161 AS icd_procedure_code11,
        TO_DATE($162, 'DD-MON-YYYY') AS procedure_date11,
        $163 AS icd_procedure_code12,
        TO_DATE($164, 'DD-MON-YYYY') AS procedure_date12,
        $165 AS icd_procedure_code13,
        TO_DATE($166, 'DD-MON-YYYY') AS procedure_date13,
        $167 AS icd_procedure_code14,
        TO_DATE($168, 'DD-MON-YYYY') AS procedure_date14,
        $169 AS icd_procedure_code15,
        TO_DATE($170, 'DD-MON-YYYY') AS procedure_date15,
        $171 AS icd_procedure_code16,
        TO_DATE($172, 'DD-MON-YYYY') AS procedure_date16,
        $173 AS icd_procedure_code17,
        TO_DATE($174, 'DD-MON-YYYY') AS procedure_date17,
        $175 AS icd_procedure_code18,
        TO_DATE($176, 'DD-MON-YYYY') AS procedure_date18,
        $177 AS icd_procedure_code19,
        TO_DATE($178, 'DD-MON-YYYY') AS procedure_date19,
        $179 AS icd_procedure_code20,
        TO_DATE($180, 'DD-MON-YYYY') AS procedure_date20,
        $181 AS icd_procedure_code21,
        TO_DATE($182, 'DD-MON-YYYY') AS procedure_date21,
        $183 AS icd_procedure_code22,
        TO_DATE($184, 'DD-MON-YYYY') AS procedure_date22,
        $185 AS icd_procedure_code23,
        TO_DATE($186, 'DD-MON-YYYY') AS procedure_date23,
        $187 AS icd_procedure_code24,
        TO_DATE($188, 'DD-MON-YYYY') AS procedure_date24,
        $189 AS icd_procedure_code25,
        TO_DATE($190, 'DD-MON-YYYY') AS procedure_date25,
        $191 AS uncompensated_care_payment_amount,
        $192 AS line_number,
        $193 AS revenue_center_code,
        $194 AS hcpcs_code,
        $195 AS deductible_coinsurance_code,
        METADATA$FILENAME AS source_file_name,
        CURRENT_TIMESTAMP AS loaded_timestamp
    FROM @raw_claims_stage//customer_1_inpatient.csv
)
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_DELIMITER = '|'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);
